[build]
  command = "npm run build"
  publish = "public"

  [build.environment]
    # cache Cypress binary in local "node_modules" folder
    # so Netlify caches it
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    # set TERM variable for terminal output
    TERM = "xterm"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

    [[functions]]
  node_bundler = "esbuild"
  external_node_modules = ["some-external-library"]
  included_files = ["./path/to/external-file"]
  timeout = 10  # Set timeout to 10 seconds or higher if needed


